name = "ChatTools"
uuid = "73b6f413-8c59-437c-8b57-329bdbe43645"
authors = ["rex <1073853456@qq.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
